name: Java CI with Maven

on:
  push:
    branches: [ master ]  # This will run the action when code is pushed to the master branch
  pull_request:
    branches: [ master ]  # This will run the action on pull requests to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out a copy of your repository

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2  # This action provides the JDK/SDK versions for the job
      with:
        java-version: '8'  # The JDK version to make available on the path
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2  # Maven cache files are stored in `~/.m2` on the runner
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}  # Cache key
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Build with Maven
      run: mvn -B package --file pom.xml  # This step runs `mvn package` command
